namespace nManager.Wow.Enums
{
    public enum WoWInventorySlot
    {
        INVTYPE_AMMO,
        INVTYPE_HEAD,
        INVTYPE_NECK,
        INVTYPE_SHOULDER,
        INVTYPE_BODY,
        INVTYPE_CHEST,
        INVTYPE_ROBE,
        INVTYPE_WAIST,
        INVTYPE_LEGS,
        INVTYPE_FEET,
        INVTYPE_WRIST,
        INVTYPE_HAND,
        INVTYPE_FINGER,
        INVTYPE_TRINKET,
        INVTYPE_CLOAK,
        INVTYPE_WEAPON,
        INVTYPE_SHIELD,
        INVTYPE_2HWEAPON,
        INVTYPE_WEAPONMAINHAND,
        INVTYPE_WEAPONOFFHAND,
        INVTYPE_HOLDABLE,
        INVTYPE_RANGED,
        INVTYPE_THROWN,
        INVTYPE_TABARD,
        INVTYPE_BAG,
    }
}
