CREATE TABLE `gameobject` (
  `guid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `entry` int(11) unsigned NOT NULL DEFAULT '0',
  `map` int(10) unsigned NOT NULL DEFAULT '0',
  `x` float NOT NULL DEFAULT '0',
  `y` float NOT NULL DEFAULT '0',
  `z` float NOT NULL DEFAULT '0',
  `o` float NOT NULL DEFAULT '0',
  `r0` float NOT NULL DEFAULT '0',
  `r1` float NOT NULL DEFAULT '0',
  `r2` float NOT NULL DEFAULT '0',
  `r3` float NOT NULL DEFAULT '0',
  `m11` float NOT NULL,
  `m12` float NOT NULL,
  `m13` float NOT NULL,
  `m14` float NOT NULL,
  `m21` float NOT NULL,
  `m22` float NOT NULL,
  `m23` float NOT NULL,
  `m24` float NOT NULL,
  `m31` float NOT NULL,
  `m32` float NOT NULL,
  `m33` float NOT NULL,
  `m34` float NOT NULL,
  `m41` float NOT NULL,
  `m42` float NOT NULL,
  `m43` float NOT NULL,
  `m44` float NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
